### PR TITLE
[#9] Fix .rewind issue in Rails

### LINKED ISSUE #9: When using Ralyxa as part of a Rails application, calling `rewind` on a requests body causes an error.
We should try to call rewind only if rewind exists to prevent this error 👎 

This is because the Rails request object handles reading differently

### PR DESCRIPTION
**Pull request by mattrayner**
When using Ralyxa as part of Rails, the `#rewind` method is not available on `request.body`.

I've added a safe navigation catch to ensure an error is not caused.

Safe navigation was added in Ruby 2.3.0 so conforms to our version limits.

Fixed #9.

### CODE REVIEW

File: lib/ralyxa/request_entities/request.rb [hunk 1]
```diff
@@ -15,7 +15,7 @@ class Request
 
       def initialize(original_request, user_class = Ralyxa::RequestEntities::User)
         @request = JSON.parse(original_request.body.read)
-        original_request.body.rewind
+        original_request.body&.rewind
```
Comment (sjmog) [inline lib/ralyxa/request_entities/request.rb]: This is a good solution but the intent isn't so clear. Can we use a private method like `conditionally_rewind_request_if_rack_didnt_do_it(request)`?

Comment (mattrayner) [reply lib/ralyxa/request_entities/request.rb]: I'll update as per your comments
